
apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: terraform-eks-eksctl
  description: Terraform-based Amazon EKS cluster provisioning using eksctl
  annotations:
    github.com/project-slug: rajudruva2/terraform-eks-eksctl

spec:
  type: infrastructure
  lifecycle: experimental
  owner: rajudruva2
